import i18n from '../lang/index'
const rules = {
    name: { required: true, message: i18n.t('m.rules.name'), trigger: 'blur'},
    userName: { required: true, message: i18n.t('m.rules.account'), trigger: 'blur'},
    password: { required: true, message: i18n.t('m.rules.account'), trigger: 'blur'},
    role: { required: true, message: i18n.t('m.rules.roleName'), trigger: 'blur'},
    sex: { required: true, message: i18n.t('m.rules.gender'), trigger: 'blur'},
    oldPassword: { required: true, message: i18n.t('m.rules.oldPassword'), trigger: 'blur'},
    newPassword: { required: true, message: i18n.t('m.rules.newPassword'), trigger: 'blur'},
    jobNumber: { required: true, message: i18n.t('m.rules.jobNumber'), trigger: 'blur'},
    number: { required: true, message: i18n.t('m.rules.number'), trigger: 'blur'},
    company: { required: true, message: i18n.t('m.rules.company'), trigger: 'blur'},
    school: { required: true, message: i18n.t('m.rules.school'), trigger: 'blur'},
    corporationId: { required: true, message: i18n.t('m.rules.company'), trigger: 'blur'},
    phone: { required: true, message: i18n.t('m.rules.phone'), trigger: 'blur'},
    chargeMan: { required: true, message: i18n.t('m.rules.chargeMan'), trigger: 'blur'},
    departmentName: { required: true, message: i18n.t('m.rules.department'), trigger: 'blur'},
    class: { required: true, message: i18n.t('m.rules.class'), trigger: 'blur'},
    departmentId: { required: true, message: i18n.t('m.rules.department'), trigger: 'blur'},
    // departmentDesc: { required: true, message: i18n.t('m.rules.department'), trigger: 'blur'},
    address: { required: true, message: i18n.t('m.rules.address'), trigger: 'blur'},
    deviceName: { required: true, message: i18n.t('m.rules.deviceName'), trigger: 'blur'},
    macId: { required: true, message: i18n.t('m.rules.macAddress'), trigger: 'blur'},
    type: { required: true, message: i18n.t('m.rules.type'), trigger: 'blur'},
    peopleNum: { required: true, message: i18n.t('m.rules.peopleNum'), trigger: 'blur'},
    periodId: { required: true, message: i18n.t('m.rules.periodId'), trigger: 'blur'},
    checkTime:{ required: true, message: i18n.t('m.rules.checkTime'), trigger: 'blur'},
    appName:{ required: true, message: i18n.t('m.rules.appName'), trigger: 'blur'},
    fileVersion:{ required: true, message: i18n.t('m.rules.fileVersion'), trigger: 'blur'},
    level:{ required: true, message: i18n.t('m.rules.level'), trigger: 'blur'},
    mediaId:{ required: true, message: i18n.t('m.rules.mediaId'), trigger: 'blur'},
    fileVersionName:{ required: true, message: i18n.t('m.rules.fileVersionName'), trigger: 'blur'},
  };
  export default rules